spring.application.name=gateway

server.port=9090

#HMS
spring.cloud.gateway.routes[0].id=HMS
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter

