spring.application.name=gateway

server.port=9090

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcros.cros-configurations[/**].allowedMethods=GET, POST, PUT, DELETE
spring.cloud.gateway.globalcros.cros-configurations[/**].allowedHeaders=*

#HMS
spring.cloud.gateway.routes[0].id=HMS
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter

