spring.application.name=HMS

spring.datasource.url=jdbc:mysql://localhost:3306/hms
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

USER_ALREADY_EXISTS = User already exists!
USER_NOT_FOUND = User not found!
PATIENT_ALREADY_EXISTS = Patient already exists!
PATIENT_NOT_FOUND = Patient not found!
DOCTOR_ALREADY_EXISTS = Doctor already exists!
DOCTOR_NOT_FOUND = Doctor not found!
INVALID_CREDENTIALS = Invalid credentials!
